### ISSUE TITLE
很期待fuzz部分~

### ISSUE THREAD

**Issue by yuuuuu422** [lazybootsafe/Go-Learning-With-Hack#4]
师傅什么时候更新呢，非常期待fuzz部分的学习。

**Comment by lazyb00tsafe** [comment]
已经移到另一本书里面了，是go py lua的安全研发的书，目前还没有开源，还在录视频，水平不行。 ---- 回复的原邮件 ***@***.***>发送日期2021年05月14日 00:21 ***@***.***> ***@***.***>主题[lazybootsafe/Go-Learning-With-Hack] 很期待fuzz部分~ (#4)

师傅什么时候更新呢，非常期待fuzz部分的学习。



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/lazybootsafe/Go-Learning-With-Hack/issues/4",

"url": "https://github.com/lazybootsafe/Go-Learning-With-Hack/issues/4",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by lazybootsafe** [comment]
已经移到另一本书里面了，是go lua py的安全研发的书，目前是私有项目，尚未开源，毕竟太菜了
